### ISSUE TITLE
Missing icon for tar.xz

### ISSUE THREAD

**Issue by LiSongMWO** [newhoa/victory-icon-theme#7]
Other archive types (zip, tar.gz, tar.bz) have archive icons but tar.xz doesn't and falls back to default.

![image](https://user-images.githubusercontent.com/5306929/27635092-1442a2de-5c06-11e7-8a86-611be1390e80.png)

**Comment by newhoa** [comment]
Thanks, this will be fixed in the next upload. For a temporary fix if you'd like, just go to the victory-icon-theme folder, and under the mimes folders (48, 64, etc), just make a copy of the archive icon and name it "application-x-xz-compressed-tar.svg" -- it'll be generic for now but it's better than the default fall back.
